name: Rust test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: git submodule update --init --recursive
      - run: cargo fmt -- --check
      - run: cargo clippy --all-features -- -D warnings
      - run: cargo test --all-features
